### ISSUE TITLE
403 responose

### ISSUE THREAD

**Issue by dl7ata** [garymcm/wsprnet_api#5]
Hi there,

first part in python example - receiving a token  - works. Second part received a 
_403 <Response [403]>_
and in HTML response 
_ "...div class="content">
    You are not authorized to access this page.  </div> "_
Any idea?

**Comment by peterbmarks** [comment]
Has your username/password been approved for API access?

**Comment by dl7ata** [comment]
No, it havn't. How does it work? I didn't find something on the side.

**Comment by peterbmarks** [comment]
"At this point in time the API is invite only. Please send me a note if you want to be included. There are some infrastructure concerns that we need to deal with before we open this up." - the start of the readme.

**Comment by dl7ata** [comment]
Sorry, I didn't recognize it and will send you a note.
Thanks!
